services:
  - type: web
    name: people-counter
    env: python
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements_render.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    healthCheckPath: /
