services:
  - type: web
    name: people-counter
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements_render.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
    healthCheckPath: /
